
on:
  pull_request:
  push:
    branches: [master]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set env vars
        run: |
          if [ ${{ github.ref }} == 'refs/heads/master' ]; then
            echo "This is a master branch"
            echo "TAG=latest" >> "$GITHUB_ENV"
          else
            echo "This is a feature branch"
            echo "TAG=dev" >> "$GITHUB_ENV"
          fi

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: abhiaws/torrentapi:${{ env.TAG }}

      - name: Deploy
        run: |
          if [ ${{ github.ref }} == 'refs/heads/master' ]; then
            echo "This is a master branch"
            echo "deploy_url=${{ secrets.RENDER_DEPLOY_HOOK_URL }}" >> "$GITHUB_ENV"
          else
            echo "This is a feature branch"
            echo "deploy_url=${{ secrets.RENDER_DEPLOY_HOOK_DEV_URL }}" >> "$GITHUB_ENV"
          fi

          curl ${{ env.deploy_url }}